pipeline {
    agent any
    stages {
        stage('Pull from Docker Hub') {
            steps {
                sh 'docker pull femelloffm/spring-calculator:1.0'
            }
        }
        stage('Remove old container') {
            when {
                not {
                    expression {
                        return sh(returnStdout: true, script: 'docker ps -a -f name=spring-calculator -q').trim() == ""
                    }
                }
            }
            steps {
                sh 'docker stop spring-calculator'
                sh 'docker rm spring-calculator'
            }
        }
        stage('Run Docker container') {
            steps {
                sh 'docker run --name spring-calculator -p 8083:8080 -d femelloffm/spring-calculator:1.0'
            }
        }
    }
}